from openpyxl import Workbook
import pandas as pd
import os

def create_excel_file(filename):
    # Create initial excel file
    wb = Workbook()
    ws = wb.active

    ws.append(["This xlsx was generated by BMScripts"])
    wb.save(filename)

def write_excel_file(filename, command, stats, sheetname):
    with pd.ExcelWriter(filename, engine='openpyxl', mode='a', if_sheet_exists="overlay") as writer:
        if sheetname in writer.book.sheetnames:
            sheet = writer.sheets[sheetname]
        else:
            sheet = writer.book.create_sheet(title=sheetname)
        sheet.cell(column=1, row=sheet.max_row + 2, value=command)
        stats.to_excel(writer, sheet_name=sheet.title, startrow=sheet.max_row)

def save_to_excel(name, command, stats, sheetname):
    print(f"Saving to {name}.xlsx")
    name = name + ".xlsx"
    if not os.path.exists(name):
        create_excel_file(name)
    write_excel_file(name, command, stats, sheetname)
